name: Wallet test
on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: pmoradis/computational-workflows:latest
    
  steps:
  - name: Checkout code
    users: actions/checkout@v2
    
  - name: Run tests
    run: |
      python3 -m pytest
